In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print('Setup is complete')

Setup is complete

In [4]:
# First make the 50 students data
np.random.seed(42) # I use this for the same data every time

num_students = 50

maths = np.random.randint(35,100,num_students)
english = np.random.randint(35,100,num_students)
science = np.random.randint(35,100,num_students)
sst = np.random.randint(35,100,num_students)
hindi = np.random.randint(35,100,num_students)

print('Maths marks: ',maths)
print('No of students: ',len(maths))

Maths marks:  [86 49 95 55 58 37 56 87 36 64 72 36 98 94 55 67 92 56 83 93 76 94 49 96
 96 81 96 85 89 98 37 85 41 55 73 52 38 94 48 43 87 36 94 78 42 81 69 70
 84 38]
No of students:  50

In [7]:
# Fifty students names
student_names = [
    "Aarav Sharma", "Vivaan Gupta", "Aditya Singh", "Vihaan Kumar", "Arjun Verma",
    "Sai Patel", "Reyansh Mehta", "Ayaan Joshi", "Krishna Nair", "Ishaan Rao",
    "Ananya Iyer", "Diya Chopra", "Priya Mishra", "Riya Shah", "Anvi Pandey",
    "Saanvi Dubey", "Myra Tiwari", "Aarohi Jain", "Kavya Agarwal", "Pooja Reddy",
    "Rohit Yadav", "Mohit Sharma", "Amit Singh", "Sumit Kumar", "Ravi Verma",
    "Ajay Patel", "Vijay Mehta", "Sanjay Joshi", "Rakesh Nair", "Mahesh Rao",
    "Neha Iyer", "Sneha Chopra", "Rekha Mishra", "Geeta Shah", "Sunita Pandey",
    "Kavita Dubey", "Meena Tiwari", "Seema Jain", "Radha Agarwal", "Lata Reddy",
    "Harsh Yadav", "Kunal Sharma", "Nikhil Singh", "Rahul Kumar", "Gaurav Verma",
    "Shivam Patel", "Pranav Mehta", "Dhruv Joshi", "Yash Nair", "Dev Rao"
]

print('Total: ',len(student_names))
print('First: ',student_names[0])
print('Last: ',student_names[-1])

Total:  50
First:  Aarav Sharma
Last:  Dev Rao

In [ ]:
# Now we make the dataframe

df = pd.DataFrame({
    'Student name': student_names,
    'Maths': maths,
    'English' : english,
    'Hindi' : hindi,
    'SST' : sst,
    'Science' : science
})

df.head()

   Student name  Maths  English  Hindi  SST  Science
0  Aarav Sharma     86       36     82   37       39
1  Vivaan Gupta     49       40     37   90       48
2  Aditya Singh     95       88     54   93       61
3  Vihaan Kumar     55       38     58   36       43
4   Arjun Verma     58       88     88   36       49

In [13]:
df['Total'] = df['Maths']+df['English']+df['SST']+df['Science']+df['Hindi']
df.head()

df['Percentage'] = (df['Total']/500)*100
df.head()

   Student name  Maths  English  Hindi  SST  Science  Total  Percentage
0  Aarav Sharma     86       36     82   37       39    280        56.0
1  Vivaan Gupta     49       40     37   90       48    264        52.8
2  Aditya Singh     95       88     54   93       61    391        78.2
3  Vihaan Kumar     55       38     58   36       43    230        46.0
4   Arjun Verma     58       88     88   36       49    319        63.8

In [14]:
def grade(per):
    if per>90:
        return 'A+'
    elif per>80:
        return 'A'
    elif per>70:
        return 'B'
    elif per>60:
        return 'C'
    elif per>50:
        return 'D'
    elif per>36:
        return 'E'
    else:
        return 'Fail'

In [15]:
df['Grade'] = df['Percentage'].apply(grade)
df.head()

   Student name  Maths  English  Hindi  SST  Science  Total  Percentage Grade
0  Aarav Sharma     86       36     82   37       39    280        56.0     D
1  Vivaan Gupta     49       40     37   90       48    264        52.8     D
2  Aditya Singh     95       88     54   93       61    391        78.2     B
3  Vihaan Kumar     55       38     58   36       43    230        46.0     E
4   Arjun Verma     58       88     88   36       49    319        63.8     C

In [16]:
df['Rank'] = df['Total'].rank(ascending=False,method='min').astype(int)
df.head()

,Student name,Maths,English,Hindi,SST,Science,Total,Percentage,Grade,Rank
0,Aarav Sharma,86,36,82,37,39,280,56.0,D,46
1,Vivaan Gupta,49,40,37,90,48,264,52.8,D,47
2,Aditya Singh,95,88,54,93,61,391,78.2,B,3
3,Vihaan Kumar,55,38,58,36,43,230,46.0,E,50
4,Arjun Verma,58,88,88,36,49,319,63.8,C,32

In [17]:
topper = df.loc[df["Total"].idxmax()]

print("🏆 School Topper")
print(topper)

🏆 School Topper
Student name    Riya Shah
Maths                  94
English                96
Hindi                  95
SST                    89
Science                63
Total                 437
Percentage           87.4
Grade                   A
Rank                    1
Name: 13, dtype: object